# Dit is een test workflow voor dbt in github.
# test
name: Test-withfailure

on:
  push:
    branches:
      - Walkthrough
  pull_request:
    branches:
     - Walkthrough

  workflow_dispatch:


jobs:
    tests:
        runs-on: windows-latest

        steps: 
            - uses: actions/checkout@v2

            - name: set up pythion in vm
              uses: actions/setup-python@v2
              with:
                 python-version: '3.9'

            - name: Install sqlfluff
              run:  pip install sqlfluff

            - name: run sqlfluf 
              run: sqlfluff lint models/* --dialect 
              
    handle-failure:
      runs-on: windwos-latest
      needs: tests
      if: ${{ failure() }}
      steps:
       - name: Notify failure
         run: echo "The dbt-sqlfluf failed"