# trigger if test fails

name: trigger-on-failure

on:
    workflow_run:
        workflows: ["test-raw-orders"]
        types:
         - completed


jobs: 
    handle-failure:
        if: ${{ github.event.workflow_run.conclusion == 'failure'}}
        runs-on: windows-latest

        steps:
            - name: Notify failure
              run: echo "The dbt-sqlfluf failed"